"""users + auth_local

Revision ID: 8a84e487d0ef
Revises: 480f4f2aa01d
Create Date: 2025-10-15 16:55:14.289617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a84e487d0ef'
down_revision: Union[str, Sequence[str], None] = '480f4f2aa01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_local_email'), 'auth_local', ['email'], unique=True)
    op.create_index(op.f('ix_auth_local_user_id'), 'auth_local', ['user_id'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False))
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_auth_local_user_id'), table_name='auth_local')
    op.drop_index(op.f('ix_auth_local_email'), table_name='auth_local')
    op.drop_table('auth_local')
    # ### end Alembic commands ###
